sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qt5-qmake libzmq3-dev libprotobuf-dev libyaml-cpp-dev libboost-dev

script:
  - qmake
  - make

language: cpp
